name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env: 
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   
    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v4

      - name: install dependencies for webshot2
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies with renv
        uses: r-lib/actions/setup-renv@v2

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: tinytex libertinus-fonts workaround
        run: ~/.TinyTeX/bin/x86_64-linux/tlmgr install libertinus-fonts
  
      - name: Install Computo extension for Quarto
        run: quarto add --no-prompt computorg/computo-quarto-extension

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PROFILE: R
